export const EARNING_TYPES = {
  BASIC_PAY: "BASIC_PAY",
  OVERTIME: "OVERTIME",
  NIGHT_PREMIUM: "NIGHT_PREMIUM",
  REGULAR_HOLIDAY: "REGULAR_HOLIDAY",
  SPECIAL_HOLIDAY: "SPECIAL_HOLIDAY",
  EXTENDED_DUTY: "EXTENDED_DUTY",
  FOOD_ALLOWANCE: "FOOD_ALLOWANCE",
  ADJUSTMENT_EARNINGS: "ADJUSTMENT_EARNINGS",
  ADJUSTMENT_ALLOWANCE: "ADJUSTMENT_ALLOWANCE",
};
