import React from "react";

export default function PrintableReport({
  title,
  subtitle,
  children,
}) {
  return (
    <div className="print-area bg-white p-6">
      {/* HEADER */}
      <div className="mb-6">
        <h1 className="text-xl font-bold text-center">
          TAGUM DOCTORS HOSPITAL
        </h1>
        <p className="text-center text-sm text-gray-600">
          {title}
        </p>
        <p className="text-center text-sm mt-1">
          {subtitle}
        </p>
        <hr className="mt-4" />
      </div>

      {/* CONTENT */}
      {children}

      {/* FOOTER */}
      <div className="mt-6 text-xs text-gray-500 flex justify-between">
        <span>Generated by Payroll System</span>
        <span>{new Date().toLocaleString()}</span>
      </div>
    </div>
  );
}
